AVAILABLE = "available"
COMPONENT_ID = "component_id"
COMPONENT_NAME = "component_name"
FOOTER_TEMPLATE = "footer_template"
HARDWARE_TYPE = "hardware_type"
HEADER_TEMPLATE = "header_template"
LOCATION = "location"
NAME = "name"
NODE = "node"
NODE_TEMPLATE = "node_template"
NOW = "now"
TRUE = "true"
X = "x"
Y = "y"
Z = "z"

NODE_NAME = "node{{:0{}d}}"

SSH_CONFIG_TEMPLATE = "./ssh-templates/ssh-config.template"
HOST_CONFIG_TEMPLATE = "./ssh-templates/host.template"
IDENTITY_FILE = "~/.ssh/twist.cert"
