AVAILABLE = "available"
COMPONENT_ID = "component_id"
COMPONENT_NAME = "component_name"
FOOTER_TEMPLATE = "footer_template"
HARDWARE_TYPE = "hardware_type"
HEADER_TEMPLATE = "header_template"
LOCATION = "location"
NAME = "name"
NODE = "node"
NODE_TEMPLATE = "node_template"
NOW = "now"
TRUE = "true"
X = "x"
Y = "y"
Z = "z"
NETWORK_HEADER = "network_header"
NETWORK_FOOTER = "network_footer"
NETWORK_TEMPLATE = "network_template"

NODE_NAME = "node{}"

SSH_CONFIG_TEMPLATE = "./templates/ssh-config.template"
HOST_CONFIG_TEMPLATE = "./templates/host.template"
IDENTITY_FILE = "~/.ssh/iminds.cert"
PROXY_COMMAND_TEMPLATE = "./templates/proxy-command.template"

ANSIBLE_CONFIG_TEMPLATE = "./templates/ansible-cfg.template"
INVENTORY_CONFIG_TEMPLATE = "./templates/ansible-inventory.template"
ANSIBLE_HOST_TEMPLATE = "./templates/ansible-host.template"
