#!/usr/bin/env bash

testbed_exists=`echo $@ | grep testbed`
if [ "$testbed_exists" == "" ]; then
	testbed="twist"
else
	testbed=`echo $@ | sed -e "s/^.*testbed=\([a-zA-Z0-9]\+\).*$/\1/g"`
fi

. ./setenv.sh $testbed

if [ $# -ge 1 ]; then
	playbook=$1
	if [ $# -ge 2 ]; then
		shift
		args="--extra-vars \"$@\""
	fi
else
	playbook=echo-hostname.yaml
	args=""
fi

IOF_FOLDER=${HOME_FOLDER}/iof-tools/

ssh -A -F ${CONFIG_FILE} ${MASTER_NODE} "bash -ic 'cd ${IOF_FOLDER} && ansible-playbook $playbook $args'"
