---
- hosts: nodes,!node0
  tasks:
    - name: set variables 1
      set_fact:
        home_dir: "{{ ansible_env.HOME }}"
        bird_folder: "iof-bird-daemon"
    - name: set variables 2
      set_fact:
        bird_dir: "{{ home_dir }}/{{ bird_folder }}"
    - name: install python3
      become: true
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - python3.6
    - name: set python3 as default
      become: true
      command: update-alternatives --install /usr/bin/python python /usr/bin/python3.6 2
    - name: create bird directory
      file:
        path: "{{ bird_dir }}"
        state: directory
        mode: '0755'
    - name: copy bird binary
      copy:
        src: "{{ bird_dir }}/bird"
        dest: "{{ bird_dir }}/"
        mode: "0755"
